#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# and replace 3rd and 7th ite with something else

x=0

while [ $x -lt 10 ]; do
	if [ $x -eq 3 ]; then
		echo "bad luck"
	elif [ $x -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$((x+1))
done
